### ISSUE TITLE
Izbor lekara

### ISSUE THREAD

**Issue by aaleksandras** [One-E2-Team/Hospital_IS#30]
Kao pacijent,
Zelim mogucnost izbora lekara,
Kako bi me lecio onaj u koga imam najvise poverenja.

* [ ] Prikazati sve lekare koje je moguce izabrati
* [ ] Prikazati prosecnu ocenu lekara dobijenu ocenom pacijenata

**Comment by FmasterofU** [comment]
Pacijent moze da bira ljekara (general practice) kod koga ce da zakaze termin.
