### ISSUE TITLE
Azuriranje rezultata testova

### ISSUE THREAD

**Issue by aaleksandras** [One-E2-Team/Hospital_IS#31]
Kao pacijent,
Zelim da redovno online azuriram svoje rezultate testova, npr. na secer,
Kako bi lekar imao uvid u napredak mog zdravlja bez bespotrebnih odlazaka u bolnicu.

* [ ] Poslati notifikaciju o promeni lekaru koji vodi terapiju i lecenje

**Comment by FmasterofU** [comment]
Dio zdravstvenog kartona/ pacijent sam zakazuje termin za sebe/ visak informacija u sistemu/ ovo je funkcinalnost kalendara/ sheet funkcionalnost

U slucaju ponovnog otvaranja ovog user storyja razmisliti o mogucnosti "uvozenja" informacija i third party servisa
