### ISSUE TITLE
Promena izabranog lekara

### ISSUE THREAD

**Issue by aaleksandras** [One-E2-Team/Hospital_IS#46]
Kao pacijent,
Zelim mogucnost promene izabranog lekara,
Kako bih u svakom momentu imao uslugu kakvu zelim.

* [ ] Omoguciti menjanje izabranog lekara najranije mesec dana od trenutka poslednje promene.
* [ ] Omoguciti prikaz svih lekara koje je moguce izabrati
* [ ] Za svakog lekara prikazati prosecnu ocenu na osnovu ocena pacijenata

**Comment by FmasterofU** [comment]
NUKE DIS!
