### ISSUE TITLE
Kreiranje guest naloga

### ISSUE THREAD

**Issue by BoKna031** [One-E2-Team/Hospital_IS#60]
Kao sekretar,
Mogu da kreiram privremeni nalog korisniku sa kojim mu zakazujem termin,
Kako bih mogao brzo i efikasno da zakazem termin pacijentu koji nema nalog i nije u mogucnosti da ga napravi

- Obezbediti unos identifikacionih podataka pacijenta

**Comment by FmasterofU** [comment]
Uklonjena funkcionalnost
